### ISSUE TITLE
Test failing on CI when re-running last build

### ISSUE THREAD

**Issue by harlantwood** [digitalbazaar/jsonld.js#156]
I forked the repo and ran tests on travis and got failures under all node versions: https://travis-ci.org/CoMakery/jsonld.js/builds/180316756

I suppose this must be that dependencies have changed in the 4 months since the build succeeded on the exact same code...

sample failures:

```
  1) JSON-LD JSON-LD Test Suite Framing #t0023 No match if node has a property where frame has an empty array for that same property.:
      AssertionError: { '@context': { ex: 'http://example.org/' }, '@graph': [] } deepEqual { '@context': { ex: 'http://example.org/' },
  '@graph': [ { '@id': 'ex:Sub1', 'ex:p': null, 'ex:q': 'bar' } ] }
      + expected - actual
       {
         "@context": {
           "ex": "http://example.org/"
         }
      -  "@graph": []
      +  "@graph": [
      +    {
      +      "@id": "ex:Sub1"
      +      "ex:p": [null]
      +      "ex:q": "bar"
      +    }
      +  ]
       }
      
      at Object.compareExpectedJson [as compare] (tests/test.js:468:12)
      at callback (tests/test.js:334:20)
      at js/jsonld.js:591:11
      at cleanup (js/jsonld.js:231:5)
      at js/jsonld.js:164:7
      at js/jsonld.js:2043:5
      at finished (js/jsonld.js:6780:7)
      at retrieve (js/jsonld.js:6786:7)
      at _retrieveContextUrls (js/jsonld.js:6885:3)
      at Function.jsonld.processContext (js/jsonld.js:2033:3)
      at js/jsonld.js:149:12
      at js/jsonld.js:133:9
      at _combinedTickCallback (internal/process/next_tick.js:67:7)
      at process._tickCallback (internal/process/next_tick.js:98:9)
  2) JSON-LD JSON-LD Test Suite Framing #t0027 Recursively, replace all key-value pairs in compacted results where the key is @preserve with the value from the key-pair. If the value from the key-pair is @null, replace the value with null.:
     TypeError: Cannot use 'in' operator to search for '@omitDefault' in undefined
      at _getFrameFlag (js/jsonld.js:5073:23)
      at _frame (js/jsonld.js:5003:27)
      at Processor.frame (js/jsonld.js:3116:3)
      at js/jsonld.js:570:36
      at js/jsonld.js:367:7
      at finished (js/jsonld.js:6780:7)
      at retrieve (js/jsonld.js:6786:7)
      at _retrieveContextUrls (js/jsonld.js:6885:3)
      at expand (js/jsonld.js:324:5)
      at js/jsonld.js:303:5
      at _combinedTickCallback (internal/process/next_tick.js:67:7)
      at process._tickCallback (internal/process/next_tick.js:98:9)

```

Lots more here: https://travis-ci.org/CoMakery/jsonld.js/builds/180316756

**Comment by jeroenooms** [comment]
Right I am seeing [similar errors](https://github.com/ropensci/jsonld/blob/master/tests/testthat/report.md). I don't think https://github.com/digitalbazaar/jsonld.js/pull/158 fixes it.

**Comment by davidlehn** [comment]
I added support to skip the 1.1 and framing tests so that part should work for now.

It's also cheating and skipping the failing RFC3986 tests.  An issue was opened for that:
https://github.com/digitalbazaar/jsonld.js/issues/160

**Comment by dlongley** [comment]
This should be fixed now, closing.
