### ISSUE TITLE
Compacting with mapped @id and @type fails

### ISSUE THREAD

**Issue by jmatsushita** [digitalbazaar/jsonld.js#167]
From `0.4.10` compacted output with mapped `@id` and `@type` returns an `untitled` key.

Submitting failing test.

**Comment by jmatsushita** [comment]
The updated test in json-ld/json-ld.org#464 fails with the following error message

```
  1) JSON-LD JSON-LD Test Suite Compaction #t0073 Ensure that compaction works with mapped @id and @type:

      AssertionError: { '@context': { id: { '@type': '@id', '@id': '@id' } },
  undefined: '../../.org/anno9',
  'http://example.org/property': 'blah' deepEqual { '@context': { id: { '@type': '@id', '@id': '@id' } },
  id: 'http://example.org/anno9',
  'http://example.org/property': 'blah
      + expected - actual

             "@type": "@id"
           }
         }
         "http://example.org/property": "blah"
      -  "undefined": "../../.org/anno9"
      +  "id": "http://example.org/anno9"
       }

      at Object.compareExpectedJson [as compare] (tests/test.js:515:12)
      at callback (tests/test.js:381:20)
      at cleanup (js/jsonld.js:231:5)
      at js/jsonld.js:164:7
      at js/jsonld.js:2045:5
      at finished (js/jsonld.js:6782:7)
      at retrieve (js/jsonld.js:6788:7)
      at _retrieveContextUrls (js/jsonld.js:6887:3)
      at Function.jsonld.processContext (js/jsonld.js:2035:3)
      at js/jsonld.js:149:12
      at js/jsonld.js:367:7
      at finished (js/jsonld.js:6782:7)
      at retrieve (js/jsonld.js:6788:7)
      at _retrieveContextUrls (js/jsonld.js:6887:3)
      at expand (js/jsonld.js:324:5)
      at done (js/jsonld.js:294:9)
      at Object.localLoader [as documentLoader] (tests/test.js:673:14)
      at js/jsonld.js:296:29
      at _combinedTickCallback (internal/process/next_tick.js:67:7)
      at process._tickCallback (internal/process/next_tick.js:98:9)

```

**Comment by davidlehn** [comment]
@jmatsushita What was the use case for this?  There's some discussion about how to fix it in https://github.com/digitalbazaar/jsonld.js/pull/183.

**Comment by davidlehn** [comment]
Fixed via https://github.com/digitalbazaar/jsonld.js/pull/218.
