### ISSUE TITLE
Unexpected token error when requiring JSONLD

### ISSUE THREAD

**Issue by e-e-e** [digitalbazaar/jsonld.js#233]
When using node v8.1.2 I receive this error.

```
/Users/xxx/node_modules/jsonld/lib/jsonld.js:1023
  ...defaults
  ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/xxx/node_modules/jsonld/lib/index.js:9:20)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/xxx/test/markdown-to-triples.test.js:4:14)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at /Users/xxx/node_modules/mocha/lib/mocha.js:231:27
    at Array.forEach (native)
    at Mocha.loadFiles (/Users/xxx/node_modules/mocha/lib/mocha.js:228:14)
    at Mocha.run (/Users/xxx/node_modules/mocha/lib/mocha.js:536:10)
    at Object.<anonymous> (/Users/xxx/node_modules/mocha/bin/_mocha:582:18)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
```

This is because the spread operator is not valid syntax until node ^8.6.0
http://node.green/#ES2018-features-object-rest-spread-properties

**Comment by davidlehn** [comment]
PR merged and 0.5.21 released.  Thanks.
